export const GET_PATIENTS_RESPONSE = 'GET_PATIENTS_RESPONSE';
export const GET_PATIENT_RESPONSE = 'GET_PATIENT_RESPONSE';
export const ADD_NEW_PATIENT_RESPONSE = 'ADD_NEW_PATIENT_RESPONSE';
export const UPDATE_EXISTING_PATIENT_RESPONSE = 'UPDATE_EXISTING_PATIENT_RESPONSE';
export const DELETE_PATIENT_RESPONSE = 'DELETE_PATIENT_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';

export const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS';
export const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING';
export const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED';

